// **********************************************************************************************
// ***                                     !!!WARNING!!!                                      ***
// *** WARNING: AUTO GENERATED FILE! DO NOT MODIFY BY HAND! YOUR CHANGES WILL BE OVERWRITTEN! ***
// ***                                     !!!WARNING!!!                                      ***
// ***                  Generated by Peano's Python API: www.peano-framework.org              ***
// **********************************************************************************************
#pragma once

#include <string>
#include <vector>

#include "tarch/la/Vector.h"

{OPEN_NAMESPACE}
  struct {CLASSNAME};
{CLOSE_NAMESPACE}

struct {FULL_QUALIFIED_CLASSNAME} {{
  std::vector< {TYPE} >  entries;
}};
