//
// Peano4 default main header file 
// Generated by Peano's Python API
// www.peano-framework.org
// This is generated. Be careful with adding your own stuff, i.e. ensure first
// whether file is maybe overwritten by Python generator/API.
//
#pragma once


#include <string>


/**
 * Main routine of the SPH code
 */
int main(int argc, char** argv);


{% for item in NAMESPACE -%}
  namespace {{ item }} {
{%- endfor %}
  /**
   * Only executed on global master, i.e. rank 0.
   */
  bool selectNextAlgorithmicStep();

  /**
   * Run one global step on rank. Called on each and every rank.
   */
  void step();
{% for item in NAMESPACE -%}
  }
{%- endfor %}

