// **********************************************************************************************
// ***                                     !!!WARNING!!!                                      ***
// *** WARNING: AUTO GENERATED FILE! DO NOT MODIFY BY HAND! YOUR CHANGES WILL BE OVERWRITTEN! ***
// ***                                     !!!WARNING!!!                                      ***
// ***                  Generated by Peano's Python API: www.peano-framework.org              ***
// **********************************************************************************************
#pragma once

#include <string>

{% for item in NAMESPACE -%}
  namespace {{ item }} {
{%- endfor %}
  int main(int argc, char** argv);
{% for item in NAMESPACE -%}
  }
{%- endfor %}
