include:
  - .continuous_integration/gitlab-templates.yml

stages:
  - Compiler

GCC:
  extends: .Variables
  stage: Compiler
  parallel:
    matrix:
    - multithreading: ["omp"]
  variables:
    CC: "gcc"
    CXX: "g++"
    IMAGE_TAG: "${IMAGE_TAG_GCC}"
    CONFIGURATION_OPTIONS: "-DENABLE_EXAHYPE=ON \
                            -DENABLE_LOADBALANCING=ON \
                            -DENABLE_BLOCKSTRUCTURED=ON \
                            -DENABLE_SWIFT=ON \
                            -DENABLE_PARTICLES=ON \
                            -DWITH_MULTITHREADING=$multithreading"
  trigger:
    include:
      - .continuous_integration/gitlab-cmake.yml
    strategy: depend

Intel:
  extends: .Variables
  stage: Compiler
  parallel:
    matrix:
    - multithreading: ["omp"]
  variables:
    CC: "icx"
    CXX: "icpx"
    IMAGE_TAG: "${IMAGE_TAG_INTEL}"
    CONFIGURATION_OPTIONS: "-DENABLE_EXAHYPE=ON \
                            -DENABLE_LOADBALANCING=ON \
                            -DENABLE_BLOCKSTRUCTURED=ON \
                            -DENABLE_SWIFT=ON \
                            -DENABLE_PARTICLES=ON \
                            -DWITH_MULTITHREADING=$multithreading"
  trigger:
    include:
      - .continuous_integration/gitlab-cmake.yml
    strategy: depend

LLVM:
  extends: .Variables
  stage: Compiler
  parallel:
    matrix:
    - multithreading: ["omp"]
  variables:
    CC: "clang"
    CXX: "clang++"
    IMAGE_TAG: "${IMAGE_TAG_LLVM}"
    CONFIGURATION_OPTIONS: "-DENABLE_EXAHYPE=ON \
                            -DENABLE_LOADBALANCING=ON \
                            -DENABLE_BLOCKSTRUCTURED=ON \
                            -DENABLE_SWIFT=ON \
                            -DENABLE_PARTICLES=ON \
                            -DWITH_MULTITHREADING=$multithreading"
  trigger:
    include:
      - .continuous_integration/gitlab-cmake.yml
    strategy: depend

NVIDIA:
  extends: .Variables
  stage: Compiler
  parallel:
    matrix:
    - multithreading: ["omp"]
  variables:
    CC: "nvc"
    CXX: "nvc++"
    IMAGE_TAG: "${IMAGE_TAG_NVIDIA}"
    CONFIGURATION_OPTIONS: "-DENABLE_EXAHYPE=ON \
                            -DENABLE_LOADBALANCING=ON \
                            -DENABLE_BLOCKSTRUCTURED=ON \
                            -DENABLE_SWIFT=ON \
                            -DENABLE_PARTICLES=ON \
                            -DWITH_MULTITHREADING=$multithreading"
  trigger:
    include:
      - .continuous_integration/gitlab-cmake.yml
    strategy: depend
