// **********************************************************************************************
// ***                                     !!!WARNING!!!                                      ***
// *** WARNING: AUTO GENERATED FILE! DO NOT MODIFY BY HAND! YOUR CHANGES WILL BE OVERWRITTEN! ***
// ***                                     !!!WARNING!!!                                      ***
// ***                  Generated by Peano's Python API: www.peano-framework.org              ***
// **********************************************************************************************
#pragma once

#include "AbstractAdvection.h"
#include "tarch/logging/Log.h"

namespace tutorials {namespace exahype2 {namespace advection {
  class Advection;

}}}

class tutorials::exahype2::advection::Advection: public tutorials::exahype2::advection::AbstractAdvection {
  private:
    static tarch::logging::Log   _log;

  public:
    

    

    

    
  public:
    

    

    

    

    

    

    

    
};