function(set_project_compiler_definitions project_name)
  set(MSVC_COMPILER_DEFINITIONS
      WIN32_LEAN_AND_MEAN
      _UNICODE
      UNICODE
  )

  set(LLVM_COMPILER_DEFINITIONS
    #-ftime-trace
  )

  set(GNU_COMPILER_DEFINITIONS)

  set(NVHPC_COMPILER_DEFINITIONS)

  if(MSVC)
    set(COMPILER_DEFINITIONS ${MSVC_COMPILER_DEFINITIONS})
  elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    set(COMPILER_DEFINITIONS ${LLVM_COMPILER_DEFINITIONS})
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(COMPILER_DEFINITIONS ${GNU_COMPILER_DEFINITIONS})
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    set(COMPILER_DEFINITIONS ${LLVM_COMPILER_DEFINITIONS})
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "NVHPC")
    set(COMPILER_DEFINITIONS ${NVHPC_COMPILER_DEFINITIONS})
  else()
    message(AUTHOR_WARNING "No compiler definitions set for '${CMAKE_CXX_COMPILER_ID}' compiler.")
  endif()

  target_compile_definitions(${project_name} INTERFACE ${COMPILER_DEFINITIONS})
endfunction()
